### Consulta de productos
GET http://localhost:3000/productos


### Consulta de productos por id
GET http://localhost:3000/productos/3


### Crear un producto
POST http://localhost:3000/productos
content-type: application/json

{
    "title": "Producto 3",
    "price": 100.10,
    "description": "Esto es una segunda prueba, en la que se necesitan al menos 20 caracteres",
    "category": "Categoria de prueba",
    "image": "https://www.google.com"
}